### ISSUE TITLE
Empty addresses broke map.

### ISSUE THREAD

**Issue by LucaPipolo** [wpsight/wpcasa-listings-map#12]
On `wpcasa-listing-map-functions.php:238` the markers are created and `lat` and `lng`properties are set doing:

```
'lat'   => esc_js( get_post_meta( get_the_id(), '_geolocation_lat', true ) ),
'lng'   => esc_js( get_post_meta( get_the_id(), '_geolocation_long', true ) ),
```

If a post with no address exists the `_geolocation_lat` and `_geolocation_long` fields does not exist for the relative post so values are sets to `" "`, an empty string. This cause the map to crash.

I would suggest to simply wrap the marker creation inside a conditional that checks if a `_geolocation_lat` and `_geolocation_long` are not empty, like:

```
if (get_post_meta( get_the_id(), '_geolocation_lat', true ) || get_post_meta( get_the_id(), '_geolocation_long', true ) ) {
  …
}
```

**Comment by soyluisbits** [comment]
I'm having this problem too 😞

**Comment by JoeHana** [comment]
Thanks a lot for your report. Sorry for the late reply on that. We will definitely fix that with the next version of this plugin.
